id: I0A790749
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:48:14+00:00'
last_modified: '2022-06-08T14:20:32.687095+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7537
  title: བསང་དང་གསོལ་མཆོད་སོགས་ཉེར་མཁོ་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ECF3:
      image_group_id: I3CN7539
      title: ''
      total_pages: 669
      order: 1
      base_file: ECF3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
